apiVersion: backstage.io/v1beta1
kind: Component
metadata:
  name: veriff-js-sdk
  description: JS SDK for easy integration with Veriff
  annotations:
    veriff.com/criticality: undefined
    github.com/project-slug: Veriff/veriff-js-sdk
  tags:
  - typescript
spec:
  type: library
  owner: client-tools
  lifecycle: production
